/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NewListingRouteImport } from './routes/new-listing'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as EditListingIdRouteImport } from './routes/edit-listing.$id'
import { Route as ConversationIdRouteImport } from './routes/conversation.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NewListingRoute = NewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditListingIdRoute = EditListingIdRouteImport.update({
  id: '/edit-listing/$id',
  path: '/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIdRoute = ConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/new-listing': typeof NewListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/new-listing': typeof NewListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/my-listings': typeof MyListingsRoute
  '/new-listing': typeof NewListingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/messages'
    | '/my-listings'
    | '/new-listing'
    | '/reset-password'
    | '/conversation/$id'
    | '/edit-listing/$id'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/messages'
    | '/my-listings'
    | '/new-listing'
    | '/reset-password'
    | '/conversation/$id'
    | '/edit-listing/$id'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/messages'
    | '/my-listings'
    | '/new-listing'
    | '/reset-password'
    | '/conversation/$id'
    | '/edit-listing/$id'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRoute
  MyListingsRoute: typeof MyListingsRoute
  NewListingRoute: typeof NewListingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ConversationIdRoute: typeof ConversationIdRoute
  EditListingIdRoute: typeof EditListingIdRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-listing': {
      id: '/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof NewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-listing/$id': {
      id: '/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof EditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$id': {
      id: '/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRoute,
  MyListingsRoute: MyListingsRoute,
  NewListingRoute: NewListingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ConversationIdRoute: ConversationIdRoute,
  EditListingIdRoute: EditListingIdRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
